config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources  :busket
   get '/categories' => 'categories#index'
   get '/category/:category_id/products', to: 'products#index', as: :product_list, :category_id => /\d+/
   get '/category/:category_id/product/:id', to: 'products#show', as: :product_info
   get '/ajax' => 'users#ajax'
   post '/category/:category_id/product/:product_id/comment', to: 'product_comments#create'
   get '/search/:condition/:query', to: 'search#index', as: :search
   post 'busket/add', to: 'busket#add_item', as: :busket_add
   get 'order/new', to: 'order#new_order', as: :new_order
   patch 'order/payment', to: 'order#payment', as: :payment

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/busket.rb
class Busket < ActiveRecord::Base
  validates :user_id, uniqueness: true
  belongs_to :user
  has_many :busket_products
  has_many :products, through: :busket_product
  has_many :orders
end

app/models/busket_product.rb
class BusketProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :busket
  delegate :name, :price, to: :product, prefix: true

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
require 'active_merchant'
include StripePayment
  belongs_to :user
  belongs_to :busket
  belongs_to :product
  delegate :name, to: :product, prefix: true
  delegate :price, to: :product, prefix: true

  def self.validation(credit_card, sum, orders)
    @callback = {}
    @callback[:errors] = []
    @credit_card = credit_card
    @sum = sum
    if @credit_card.validate.empty?
      @callback[:is_success] = true
    else
      @callback[:is_success] = false
      @callback[:errors] = credit_card.validate.each { |key, msg| "#{key.capitalize} #{msg.first}" } 
    end
    @callback = pay(credit_card, sum, orders, @callback)
  end

  def self.pay(credit_card, sum, orders, callback)
    if callback[:is_success]
      response = gateway.purchase(sum, credit_card)
      if response.success?
        orders.update_all(:is_paid => true) 
      end
    end
    callback
    rescue => e
      callback[:is_success] = false
      callback[:errors] << e.message
      return callback
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: {icon: "30x30", list: "300x400"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  belongs_to :category
  has_many :product_comments
  has_many :product_tags
  has_many :tags, through: :product_tags
  delegate :name, to: :category, prefix: true
  has_many :busket_products
  has_many :buskets, through: :busket_product
  has_many :buskets
  has_many :orders
end

app/models/product_comment.rb
class ProductComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  delegate :email , :to => :user
  has_many :nested_comments, foreign_key:'parent_id', class_name:'ProductComment' 
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :product
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :product_tags
  has_many :products, through: :product_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :test
  after_create :create_busket

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :product_comments
  has_one :busket
  delegate :id, to: :busket, prefix: true
  has_many :orders

  private
  def create_busket
    Busket.create(user_id: id)
  end

end

app/controllers/busket_controller.rb
class BusketController < ApplicationController
  before_filter :does_exist, :only => :add_item

  def add_item
    if does_exist == false
      @busket = BusketProduct.create(:product_id => params[:product_id], 
                                   :busket_id => current_user.busket_id, :quantity => params[:quantity])
    else
      @busket.update_attributes(:quantity => @busket.quantity + params[:quantity].to_f)
    end
    redirect_to :back
  end

  def does_exist
    @busket = BusketProduct.find_by(:product_id => params[:product_id], :busket_id => current_user.busket_id)
    @busket == nil ? false : true
  end

  def index
    @busket = Busket.find_by(:id => current_user.busket_id)
    @busket = BusketProduct.where(:busket_id => @busket.id)
  end

  def destroy
    @busket_product = BusketProduct.find_by(:id => params[:id])
    @busket_product.destroy
    render :nothing => true,  :status => 200
  end
end

app/controllers/order_controller.rb
include StripePayment
class OrderController < ApplicationController
  require 'active_merchant'
  before_filter :is_empty 

  def new_order
    if is_empty == true
      sum = 0
      product_list = ''     
      current_user.busket.busket_products.each do |p| 
        sum += p.product_price * p.quantity
        product_list += p.product_name + '; '
      end
      @order = Order.create(:sum => sum, :is_paid => false, 
                            :user_id => current_user.id, :ordered_products => product_list)
      current_user.busket.busket_products.destroy_all
      @orders = Order.where(:is_paid => false)
      render 'payment'
    else
      @orders = Order.where(:is_paid => false, :user_id => current_user.id)
      render 'payment'
    end
  end

  def payment
    @orders = Order.where(:is_paid => false, :user_id => current_user.id)
    @orders_for_payment = Order.where(:id => params[:order_ids])
    @sum = @orders_for_payment.sum(:sum)
    @credit_card = credit_card(params)
    @callback = Order.validation(@credit_card, @sum, @orders_for_payment)
    @callback[:is_success] ? flash[:notice]  = "Success" : flash[:error] = @callback[:errors]
    render 'payment', :orders => @orders
  end

  def is_empty
    current_user.busket.busket_products.count > 0 ? true : false
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@product = Product.where(:category_id => params[:category_id])
  end
  def show
  	@product = Product.find_by(:category_id => params[:category_id], :id => params[:id])
    @comment = ProductComment.new
    @comments = ProductComment.where(:product_id => params[:id], :parent_id => nil)
    
    @tags_array = []
    @product_tags = Product.find_by(:category_id => params[:category_id], :id => params[:id]).tags
    @product_tags.each do |p|
      @tags_array << {:id => p.id, :title => p.title}
    end
  end
  def tags_url

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @tag = Tag.find_by(:title => params[:query])
    @product_to_tags = ProductTag.where(:tag_id => @tag.id).pluck('product_id')
    @product = Product.where(:id => @product_to_tags)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/busket_helper.rb
module BusketHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_comments_helper.rb
module ProductCommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/busket/index.html.erb
<div class='container'>
  <h1>Your busket</h1>
    <table class='table'>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
      </tr> 
      <% @busket.each do |b| %>
      <tr class='item'>
        <td><%= b.product_name %></td>
        <td><%= b.quantity %></td>
        <td><div class='delete_icon' id='<%=b.id%>'></div></td> 
      </tr>
      <%end%>
    </table>
  <%= link_to 'Order', new_order_path %>
</div>

app/views/order/payment.html.erb
<div class='container'>
  <%= form_tag(payment_path, method: "patch") do %>
    <h2>Your busket contains these orders. Please, choose those of them that you want to buy!</h2>
    <table class='table'>
      <tr>
        <th>Products</th>
        <th>Sum</th>
      </tr>
      <% @orders.each do |o| %>
      <tr>
        <td><%= o.ordered_products %></td>
        <td><%= o.sum %></td>
        <td><%= check_box_tag 'order_ids[]', o.id%></td>
      </tr>
      <% end %>
    </table>

    <h2>Add your credit card info</h2>
      <%= label_tag :first_name, 'First name' %>
      <%= text_field_tag :first_name %><br>
      <%= label_tag :last_name, 'Last name' %>
      <%= text_field_tag :last_name %><br>
      <%= label_tag :month, 'Month' %>
      <%= number_field_tag :month, nil, in: 1...13 %><br>
      <%= label_tag :year, 'Year' %>
      <%= number_field_tag :year, nil, in: 2000...2026 %><br>
      <%= hidden_field_tag :type, "visa" %>
      <%= label_tag :number, 'Number' %>
      <%= text_field_tag :number %><br>
      <%= submit_tag 'Buy', {confirm: 'Are you sure?'} %>

    <% end %>
</div>

app/views/products/_busket_item.html.erb
<div class='container' id='add_item'>
<input type='number' id='quantity' style= width:3%>
<input type='submit' class="btn btn-info" value='To busket' id='item_busket'>
<input type='hidden' id='name_id' value=<%=product_id%> >
</div>

app/views/products/index.html.erb
<table class='table'>
  <tr>
    <th>Product name</th>
    <th>Price</th>
    <th>Image preview</th>
  </tr>
  <% @product.each do |c| %>
  <tr>
    <td><%= link_to "#{c.name}", product_info_path(:category_id => c.category_id, :id => c.id)%></td>
    <td><%= c.price %></td>
    <td><%= image_tag(c.image, size: "60x40", class: 'img-circle') %></td>
    <td><%= render '/products/busket_item', :product_id => c.id %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/products/show.html.erb
<div class="container">
<table class='table'>
  <tr>
  	<th>Description</th>
    <th>Price</th>
    <th>Image</th>
    <th>Tags</th>
  </tr>
  <tr>
  	<td><%= @product.description %></td>
    <td><%= @product.price %></td>
    <td><%= image_tag(@product.image, size: "250x200", class: 'img-circle') %></td>
    <% @tags_array.each do |t| %> 
    <td><%= link_to t[:title], search_path(:condition => 'tag', :query => t[:title]) %></td>
    <%end%>
  </tr>
</table>
<%= render '/products/busket_item', :product_id => @product.id %>
<section class="comment-list">
    <%= render '/product_comments/list', :comments => @comments %>
    <%= render '/product_comments/form', :comment => @comment, :product_id => @product.id,
                                         :category_id => @product.category_id %>
</section>
</div>