config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources  :busket
   get '/categories' => 'categories#index'
   get '/category/:category_id/products', to: 'products#index', as: :product_list, :category_id => /\d+/
   get '/category/:category_id/product/:id', to: 'products#show', as: :product_info
   get '/ajax' => 'users#ajax'
   post '/category/:category_id/product/:product_id/comment', to: 'product_comments#create'
   get '/search/:condition/:query', to: 'search#index', as: :search
   post 'busket/add', to: 'busket#add_item', as: :busket_add
   get 'order/new', to: 'order#new_order', as: :new_order
   patch 'order/payment', to: 'order#payment', as: :payment

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/busket.rb
class Busket < ActiveRecord::Base
  validates :user_id, uniqueness: true
  belongs_to :user
  has_many :busket_products
  has_many :products, through: :busket_product
  has_many :orders
end

app/models/busket_product.rb
class BusketProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :busket
  delegate :name, :price, to: :product, prefix: true

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
require 'active_merchant'
include StripePayment
  belongs_to :user
  belongs_to :busket
  belongs_to :product
  delegate :name, to: :product, prefix: true
  delegate :price, to: :product, prefix: true

  def self.validation(credit_card, sum, orders)
    @callback = {}
    @callback[:errors] = []
    @credit_card = credit_card
    @sum = sum
    if @credit_card.validate.empty?
      @callback[:is_success] = true
    else
      @callback[:is_success] = false
      @callback[:errors] = credit_card.validate.each { |key, msg| "#{key.capitalize} #{msg.first}" } 
    end
    @callback = pay(credit_card, sum, orders, @callback)
  end

  def self.pay(credit_card, sum, orders, callback)
    if callback[:is_success]
      response = gateway.purchase(sum, credit_card)
      if response.success?
        orders.update_all(:is_paid => true) 
      end
    end
    callback
    rescue => e
      callback[:is_success] = false
      callback[:errors] << e.message
      return callback
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: {icon: "30x30", list: "300x400"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  belongs_to :category
  has_many :product_comments
  has_many :product_tags
  has_many :tags, through: :product_tags
  delegate :name, to: :category, prefix: true
  has_many :busket_products
  has_many :buskets, through: :busket_product
  has_many :buskets
  has_many :orders
end

app/models/product_comment.rb
class ProductComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  delegate :email , :to => :user
  has_many :nested_comments, foreign_key:'parent_id', class_name:'ProductComment' 
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :product
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :product_tags
  has_many :products, through: :product_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :test
  after_create :create_busket

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :product_comments
  has_one :busket
  delegate :id, to: :busket, prefix: true
  has_many :orders

  private
  def create_busket
    Busket.create(user_id: id)
  end

end

app/controllers/busket_controller.rb
class BusketController < ApplicationController
  before_filter :does_exist, :only => :add_item

  def add_item
    if does_exist == false
      @busket = BusketProduct.create(:product_id => params[:product_id], 
                                   :busket_id => current_user.busket_id, :quantity => params[:quantity])
    else
      @busket.update_attributes(:quantity => @busket.quantity + params[:quantity].to_f)
    end
    redirect_to :back
  end

  def does_exist
    @busket = BusketProduct.find_by(:product_id => params[:product_id], :busket_id => current_user.busket_id)
    @busket == nil ? false : true
  end

  def index
    @busket = Busket.find_by(:id => current_user.busket_id)
    @busket = BusketProduct.where(:busket_id => @busket.id)
  end

  def destroy
    @busket_product = BusketProduct.find_by(:id => params[:id])
    @busket_product.destroy
    render :nothing => true,  :status => 200
  end
end

app/controllers/order_controller.rb
include StripePayment
class OrderController < ApplicationController
  require 'active_merchant'
  before_filter :is_empty 

  def new_order
    if is_empty == true
      sum = 0
      product_list = ''     
      current_user.busket.busket_products.each do |p| 
        sum += p.product_price * p.quantity
        product_list += p.product_name + '; '
      end
      @order = Order.create(:sum => sum, :is_paid => false, 
                            :user_id => current_user.id, :ordered_products => product_list)
      current_user.busket.busket_products.destroy_all
      @orders = Order.where(:is_paid => false)
      render 'payment'
    else
      @orders = Order.where(:is_paid => false, :user_id => current_user.id)
      render 'payment'
    end
  end

  def payment
    @orders = Order.where(:is_paid => false, :user_id => current_user.id)
    @orders_for_payment = Order.where(:id => params[:order_ids])
    @sum = @orders_for_payment.sum(:sum)
    @credit_card = credit_card(params)
    @callback = Order.validation(@credit_card, @sum, @orders_for_payment)
    @callback[:is_success] ? flash[:notice]  = "Success" : flash[:error] = @callback[:errors]
    render 'payment', :orders => @orders
  end

  def is_empty
    current_user.busket.busket_products.count > 0 ? true : false
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @tag = Tag.find_by(:title => params[:query])
    @product_to_tags = ProductTag.where(:tag_id => @tag.id).pluck('product_id')
    @product = Product.where(:id => @product_to_tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/busket_helper.rb
module BusketHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "EStore" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">EStore</a>
        </div>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "Categories", categories_path  %></li>
                <li><%= link_to "Discounts", ""  %></li>
                <li><%= link_to "Product of the month", ""  %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <%= link_to 'My Busket', busket_index_path %>
                <%= render 'devise/menu/registration_items' %>
                <%= render 'devise/menu/login_items' %>
              </ul>
            </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; EStore 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>